Fix descriptions of libraries
RedMadRobot/techradar-android pull request #21
Opened 2024-10-02 10:47 UTC by TopHlop

2024-10-02 11:55 UTC, EmogurovAnton commented on radar/2024-09-27/moshi.md
> +- Тяжелая поддержка сериализации sealed class, value class и других фишек языка Kotlin.
```suggestion
- Сложность сериализации sealed class, value class и поддержки других фишек языка Kotlin.
```

2024-10-02 11:55 UTC, EmogurovAnton commented on radar/2024-09-27/paging_3.md
> +Проблемы с короторыми можно столкнуться при использовании Paging 3:
```suggestion
Проблемы с которыми можно столкнуться при использовании Paging 3:
```

2024-10-02 11:55 UTC, EmogurovAnton commented on radar/2024-09-27/paging_3.md
> +- Нарушается принцип, что для экрана используется один источник данных (отдельный источник данных для state и для данных пагинации).
```suggestion
- Нарушается принцип использования одного источника данных на экране (отдельный источник данных для state и данных пагинации).
```

2024-10-02 11:55 UTC, EmogurovAnton commented on radar/2024-09-27/paging_3.md
> +- Очень легко допустить ошибку в настройке работы пагинации, которые можно заметить только на определенных краевых.
```suggestion
- Очень легко допустить ошибки в настройке работы пагинации, которые можно заметить только при определенных краевых.
```

2024-10-02 11:55 UTC, EmogurovAnton commented on radar/2024-09-27/kotlinx.serialization.md
> +- Поддержка из под коробки для работы с sealed class, value class и другими фишками языка Kotlin.
```suggestion
- Совместимость с sealed class, value class и другими фишками языка Kotlin.
```

2024-10-03 11:40 UTC, TopHlop commented on radar/2024-09-27/paging_3.md
> +- Очень легко допустить ошибку в настройке работы пагинации, которые можно заметить только на определенных краевых.
Поправил

2024-10-03 11:40 UTC, TopHlop commented on radar/2024-09-27/paging_3.md
> +- Нарушается принцип, что для экрана используется один источник данных (отдельный источник данных для state и для данных пагинации).
Поправил

2024-10-03 11:40 UTC, TopHlop commented on radar/2024-09-27/paging_3.md
> +Проблемы с короторыми можно столкнуться при использовании Paging 3:
Поправил

2024-10-03 11:40 UTC, TopHlop commented on radar/2024-09-27/moshi.md
> +- Тяжелая поддержка сериализации sealed class, value class и других фишек языка Kotlin.
Поправил

2024-10-04 09:46 UTC, EmogurovAnton commented on radar/2024-09-27/kotlinx.serialization.md
> +- Поддержка из под коробки для работы с sealed class, value class и другими фишками языка Kotlin.
Да, правда не очень звучит

```suggestion
- Сериализация sealed class, value class и других фишек языка Kotlin из коробки.
```

Может так, что думаешь? А то просто из под коробки звучит как-то не знаю, сразу хочется узнать, что они под этой коробкой забыли 😆

2025-07-09 15:38 UTC, sWift-sai requested changes

2025-07-09 15:38 UTC, sWift-sai commented on radar/2024-09-27/junit.md
> +TODO: Дописать плюсы
```suggestion
- Фреймворки Junit являются самыми популярными среди тестовых фреймворков, наличие какого-то опыта с ними у любого разработчика сильно выше, чем у других фреймворков (к примеру, распространенность Kotest весьма низкая), что понижает порог входа в проект на основе этих фреймворков
- Junit 5 имеет множество улучшений в сравнении с Junit 4 и без проблем работает в JVM-среде, хотя и не применим в Instrumentation-среде (в ней применим только Junit 4)
- Junit 5 наиболее надёжен, прозрачен и функционально развит в сравнении с аналогами, тк существует много лет, проверен и отлажен в результате применения мировым сообществом на большом количестве проектов, чего нельзя сказать о таких аналогах, как Kotest, Spek 2 и др.
- Junit 5 за счет широкой кастомизируемости позволяет реализовывать тесты в различных стилях, в том числе в приближенных к тем, которые доступны в Kotest и Spek 2
```

2025-07-11 09:21 UTC, EmogurovAnton approved these changes

2025-07-11 09:24 UTC, EmogurovAnton commented on radar/2024-09-27/junit.md
> +TODO: Дописать плюсы
А точки не нужны "т.к." на 12 строчке?

2025-07-23 13:53 UTC, sWift-sai commented on radar/2024-09-27/junit.md
> +TODO: Дописать плюсы
да, лучше с точками :)

2025-08-08 16:38 UTC, sWift-sai requested changes

2025-08-08 16:38 UTC, sWift-sai commented on radar/2024-09-27/kotlinx.serialization.md
> +- Поддержка из под коробки для работы с sealed class, value class и другими фишками языка Kotlin.
"из под коробки" не говорят

```suggestion
- Поддержка из коробки работы с sealed class, value class и другими фишками языка Kotlin.
```

2025-08-08 16:38 UTC, sWift-sai commented on radar/2024-09-27/moshi.md
> +- Поддержка новых версий kotlin происходит только со временем.
так чуть понятнее
```suggestion
- Поддержка новых версий kotlin появляется с задержкой.
```

2025-08-08 16:38 UTC, sWift-sai commented on radar/2024-09-27/paging_3.md
> +Проблемы с которыми можно столкнуться при использовании Paging 3:
```suggestion
Проблемы, с которыми можно столкнуться при использовании Paging 3:
```

2025-08-11 13:39 UTC, TopHlop commented on radar/2024-09-27/kotlinx.serialization.md
> +- Поддержка из под коробки для работы с sealed class, value class и другими фишками языка Kotlin.
Поправил

2025-08-11 13:39 UTC, TopHlop commented on radar/2024-09-27/moshi.md
> +- Поддержка новых версий kotlin происходит только со временем.
Поправил

2025-08-21 15:29 UTC, sWift-sai approved these changes

2025-08-22 08:52 UTC, merged