Feature/aoe update 4.3.0
RedMadRobot/techradar-android pull request #6
Opened 2024-04-01 15:47 UTC by sonulen

- [x] Обновить движок
- [x] Обновить доки
- [ ] Обновить публикацию на pages

![image](https://github.com/RedMadRobot/techradar-android/assets/18189767/f10e7367-fc3a-40a2-bda3-8ddeae8b58de)

![image](https://github.com/RedMadRobot/techradar-android/assets/18189767/bf4a917d-db4c-4cba-876d-5f789e0c430f)

2024-04-01 17:23 UTC, osipxd requested changes

2024-04-01 17:23 UTC, osipxd commented on about.md
> +GitHub: [Rmr Tech Radar on GitHub](https://github.com/RedMadRobot/techradar-android/)
Предлагаю сократить немного 
```suggestion
Материалы и исходный код тех. радара находятся на [GitHub](https://github.com/RedMadRobot/techradar-android/)
```

2024-04-01 17:23 UTC, osipxd commented on config.json
> +      "title": "Languages",
В языках у нас будет мало, поэтому я подумал, что мб фреймворки сюда перенести всё-таки? С той точки зрения, что они сильно меняют подход к разработке. Как яркий пример - Compose

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/android_lint.md
> +tags: [tooling, ci]
Мб что-то про quality добавить?
И ещё пока не до конца понимаю разницу между tooling и utilities

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/coil.md
> +tags: [library]
Мб image loading или что-то такое вместо library? А library дублирует категорию

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/dagger_2.md
> +tags: [library, di]
Предлагаю везде library убрать, если фреймворки решим унести к языкам. Если тэги регистрочувствительны, то лучше DI

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/danger.md
> +tags: [tooling, ci]
И тут CI (в случае если регистрочувствительные теги)

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/danger.md
> +tags: [tooling, ci]
\+ что-то про quality control или static analyzer

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/detekt.md
> +tags: [tooling, ci]
\+ что-то про quality control или static analyzer

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/epoxy.md
> +tags: [library]
\+ `recycler view`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/groupie.md
> +tags: [library]
\+ `recycler view`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/gson.md
> +tags: [library]
\+ `serialization`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/insetter.md
> +tags: [library]
\+ `UI`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/java.md
> +tags: [languages]
А теги обязательные? Кажется в таких случаях можно не указывать?

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/kotest.md
> +tags: [library]
\+ `unit testing`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/kotlinx.coroutines.md
> +tags: [library]
\+ `concurrency`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/kotlinx.serialization.md
> +tags: [library]
\+ `serialization`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/moshi.md
> +tags: [library]
\+ `serialization`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/room.md
> +tags: [library]
\+ `database`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/rxjava.md
> +tags: [library]
\+ `concurrency`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/security-crypto.md
> +tags: [library]
\+ `security`

2024-04-01 17:23 UTC, osipxd commented on radar/2022-04-07/timber.md
> +tags: [library, tooling]
\+ `logging`

2024-04-02 11:16 UTC, sonulen commented on radar/2022-04-07/java.md
> +tags: [languages]
не обязательные

2024-04-02 15:53 UTC, sonulen commented
Пример каким станет радар: https://sonulen.github.io/techradar/

2024-04-03 08:49 UTC, sonulen commented on config.json
> +    "showEmptyRings": true
давай уберем

2024-04-03 10:56 UTC, osipxd commented on config.json
> +      "description": "Языки и фреймворки на которые используют роботы.",
```suggestion
      "description": "Языки и фреймворки которые используют роботы.",
```

2024-04-03 11:11 UTC, osipxd approved these changes

2024-04-03 11:24 UTC, merged