Added pages about assertion libraries: junit, assertj, kotest-assertions
RedMadRobot/techradar-android pull request #8
Opened 2024-04-04 15:22 UTC by sonulen

Посмотреть результат можно тут - https://sonulen.github.io/techradar/

2024-04-11 08:08 UTC, osipxd requested changes

2024-04-11 08:08 UTC, osipxd commented on radar/2024-04-03/kotest-assertion.md
> +1. Адаптирован под Kotlin, поддерживает синтаксис `infix`, `reified`, `inline` и т.п.
Может так написать?
```suggestion
1. Поддерживает и использует фичи Kotlin: `infix`, `reified`, `inline` и т.п.
```

2024-04-11 08:08 UTC, osipxd commented on radar/2024-04-03/kotest-assertion.md
> +   _Тест выглядит как предложение, что упрощает сильно понимание происходящего._
```suggestion
   _Тест выглядит как предложение, что упрощает понимание происходящего._
```

2024-04-11 08:08 UTC, osipxd commented on radar/2024-04-03/kotest-assertion.md
> +4. Активное сообщество и регулярные обновления (4.3k звездочек на гитхабе), обеспечивающие поддержку и развитие библиотеки.
Тут инфа про кол-во звёзд все время будет устаревать

2024-04-11 08:08 UTC, osipxd commented on radar/2024-04-03/kotest-assertion.md
> +   _Кажется очень частый кейс - когда мы приводим `State` к `State.Content`_
Стоит добавить больше контекста
```suggestion
5. После проверок типа работают смарт-касты  
   _Например, это удобно когда `State` это sealed class, и нам нужно проверить именно содержимое `State.Content`._
```

2024-04-11 08:08 UTC, osipxd commented on radar/2024-04-03/kotest-assertion.md
> +2. Некоторые разработчики могут столкнуться с изучением нового синтаксиса.
В такой формулировке кажется что можно так про любую библиотеку сказать. Предлагаю либо переформулировать, либо убрать этот пункт.

2024-04-11 08:08 UTC, osipxd commented on radar/2024-04-03/junit-assertion.md
> +Junit Assertions - это классическая библиотека тестовых ассертов, встроенная в фреймворк тестирования JUnit.
Assertions это ведь просто класс внутри junit-jupiter-api? Может добавить коротенький абзац на страницу JUnit, что в ней есть ассерты, но они ограниченные поэтому нужно смотреть в сторону Kotest или AssertJ. А эту страницу удалить.

2024-04-11 10:59 UTC, sonulen commented on radar/2024-04-03/assertJ.md
> +📝 Полезные ссылки:
Сначала так и делал, но мне чет не очень нравится как выглядит

Просто текст с иконкой:
![image](https://github.com/RedMadRobot/techradar-android/assets/18189767/9a9fc1ab-9dff-4767-8312-91976bc41179)  

Заголовки второго уровня:
![image](https://github.com/RedMadRobot/techradar-android/assets/18189767/79d6f7d7-2c33-4047-bc87-d92d20eae505)

2024-04-11 18:19 UTC, sonulen commented on radar/2024-04-03/junit-assertion.md
> +Junit Assertions - это классическая библиотека тестовых ассертов, встроенная в фреймворк тестирования JUnit.
сделал в итоге как с assertj

закинул в предыдущий релиз -> а в новом релизе перевел в холд и описание добавил

2024-04-11 18:21 UTC, sonulen commented on radar/2024-04-03/kotest-assertion.md
> +2. Некоторые разработчики могут столкнуться с изучением нового синтаксиса.
убрал (потому что хз как переформулировать)

2024-04-12 15:49 UTC, sonulen commented on radar/2024-04-03/assertJ.md
> +5. Из коробки есть поддержка [BDDAssertions][bbdassertions]
Порядок нет - я скорее закладывал нумерованный чтобы видно было кол-во.

Я бы оставил, что скажешь?

2024-04-12 16:08 UTC, sonulen commented on radar/2024-04-03/kotest-assertion.md
> +➕ Плюсы:
@osipxd Оставил в итоге плюсы на каждой страничке + они же есть на странице сравнения

Дублирование инфы - да
Но так страничка выглядет гораздо _интереснее_

что думаешь?

2024-04-15 11:23 UTC, osipxd commented on radar/2024-04-03/assertJ.md
> +5. Из коробки есть поддержка [BDDAssertions][bbdassertions]
Ok

2024-04-15 11:53 UTC, osipxd commented on CONTRIBUTING.md
>  Так как страничка - это `markdown` файл - можно вставлять картинки, для этого положи ее в `./public/images/` и добави ссылку:
```suggestion
Так как страничка - это `markdown` файл - можно вставлять картинки, для этого положи ее в `./public/images/` и добавь ссылку:
```

2024-04-15 11:53 UTC, osipxd commented on CONTRIBUTING.md
>  ```markdown
Не могу оставить коммент ниже.
Можешь поменять "Подробное описание лучше заполнять по следующему шаблону:" на "При добавлении новой страницы в радар, стоит следовать шаблону:"?

2024-04-15 11:53 UTC, osipxd commented on CONTRIBUTING.md
> +При переводе в `Hold` - стоит заполнить следущий шаблон:
```suggestion
При переводе в `Hold` стоит заполнить следующий шаблон:
```

2024-04-15 11:53 UTC, osipxd commented on CONTRIBUTING.md
> +- удалить старую зависимость
Думаю не стоит так подробно описывать следующие шаги в общем. Только какие-то нюансы, иначе у нас везде будет примерно одинаковое описание для заброшенных библиотек.

2024-04-15 11:53 UTC, osipxd commented on CONTRIBUTING.md
> +Так же это может быть ссылка на документацию по миграции, для примера можно посмотреть на accompanist insets.
```suggestion
Так же это может быть ссылка на документацию по миграции, для примера можно посмотреть на [гайд миграции accompanist-insets](тут_ссылка).
```

2024-04-15 11:53 UTC, osipxd commented on CONTRIBUTING.md
> +</br>
Мб чуть компактнее сделать?
```suggestion
---
</br>
```

2024-04-15 11:53 UTC, osipxd commented on CONTRIBUTING.md
> +[assertj]: https://redmadrobot.github.io/techradar-android/libraries/assertj
Кстати, тут ссылки не получится на относительные заменить?

2024-04-15 11:53 UTC, osipxd commented on public/docs/assertions/assertj_kotest_compare.md
> +- Интеграция с AS
Душный коммент, но лучше в доках писать полностью
```suggestion
- Интеграция с Android Studio
```

2024-04-15 11:53 UTC, osipxd commented on public/docs/assertions/assertj_kotest_compare.md
> +- Сложные/вложенные структуры
```suggestion
- Cравнение сложных структур данных
```

2024-04-15 11:53 UTC, osipxd commented on public/docs/assertions/assertj_kotest_compare.md
> +## jUnit
```suggestion
## JUnit
```

2024-04-15 11:53 UTC, osipxd commented on public/docs/assertions/assertj_kotest_compare.md
> +- Поддержка фичей kotlin
```suggestion
- Поддержка фичей Kotlin
```

2024-04-15 11:53 UTC, osipxd commented on public/docs/assertions/assertj_kotest_compare.md
> +| Критерий                       | jUnit                | AssertJ                | Kotest              |
```suggestion
| Критерий                       | JUnit                | AssertJ                | Kotest              |
```

2024-04-15 11:53 UTC, osipxd commented on public/docs/assertions/assertj_kotest_compare.md
> +## Kotest
Тут и в других местах, мб стоит уточнить, что именно ассершены?
```suggestion
## Kotest Assertions
```

2024-04-15 11:53 UTC, osipxd commented on public/docs/assertions/assertj_kotest_compare.md
> +| Поддержка фичей kotlin         | ➖                   | ➖                     | ➕                  |
И тут бы синхронизировать с критериями сверху после применения комментов.

2024-04-15 11:53 UTC, osipxd commented on radar/2022-04-08/assertj.md
> +ring:       adotp
```suggestion
ring:       adopt
```

2024-04-15 11:53 UTC, osipxd commented on radar/2022-04-08/junit-assertion.md
> +title:      JUnit assertions
Меня всё ещё не отпускает ощущение, что для JUnit Assertions не нужна отдельная страница, а достаточно абзаца на странице JUnit. Того что у тебя уже написано на странице JUnit достаточно.
А потом в обновлённой странице кратко написать, что больше не используем ассерты из JUnit вместо этого используем Kotest assertions

2024-04-15 11:53 UTC, osipxd commented on radar/2024-04-03/junit-assertion.md
> +На основе [сравнения библиотек ассертов][asserts_compare] принято решение использовать [Kotest-assertions](/libraries/kotest-assertion/) для android/kotlin проектов.
Везде написание разное. Предлагаю придерживаться того, которое на странице Kotest assertions
```suggestion
На основе [сравнения библиотек ассертов][asserts_compare] принято решение использовать [Kotest assertions](/libraries/kotest-assertion/) для android/kotlin проектов.
```

2024-04-15 11:53 UTC, osipxd commented on radar/2024-04-03/junit.md
> +quadrant:   libraries
Го, сразу во фреймворк перенесём

2024-04-15 11:53 UTC, osipxd commented on radar/2024-04-03/junit-assertion.md
> +ring:       hold
Предлагаю эту страницу переименовать в junit.md и оставить adopt. Содержимое чуть поправить, чтобы было понятно, что отказались от одной из составляющих JUnit.
```suggestion
title:      JUnit
ring:       adopt
```

2024-04-15 11:53 UTC, osipxd commented on radar/2024-04-03/assertj.md
> +- 🔒 База знаний: [Глубокое погружение в тестирование](https://android.pages.redmadrobot.dev/knowledge/guide/testing/deep-dive.html)
Я вот сейчас подумал, что структура нашей доки может (и скорее всего будет) меняться и тут будет тяжко поддерживать актуальность ссылок. Может заменим на одну ссылку, кидающую на https://android.pages.redmadrobot.dev/knowledge/guide/testing/quickstart.html ?

2024-04-15 11:53 UTC, osipxd commented on radar/2024-04-03/junit.md
> +Плюсы Junit:
```suggestion
Плюсы JUnit:
```

2024-04-15 11:53 UTC, osipxd commented on radar/2024-04-03/junit.md
> +Плюсы Junit:
Поищешь какой-нибудь линтер для доков, куда можно будет загнать слова, для которых важно соблюдать одинаковое написание? Вроде что-то такое у danger видел, но это не точно

2024-04-15 11:53 UTC, osipxd commented on radar/2024-04-03/kotest-assertion.md
> +Кроме того, Kotest-assertions обладает расширяемым API, позволяющим добавлять собственные матчеры.
```suggestion
Кроме того, Kotest assertions обладает расширяемым API, позволяющим добавлять собственные матчеры.
```

2024-04-15 11:53 UTC, osipxd commented on radar/2024-04-03/kotest-assertion.md
> +➕ Плюсы:
👌

2024-04-15 11:54 UTC, osipxd commented on radar/2024-04-03/junit-assertion.md
> +Junit Assertions - это классическая библиотека тестовых ассертов, встроенная в фреймворк тестирования JUnit.
Добавил коммент в новом файле, продолжим обсуждение там

2024-04-15 11:56 UTC, osipxd commented on radar/2024-04-03/assertJ.md
> +📝 Полезные ссылки:
Да, с emoji не очень хорошо сочетается. Да и в целом ощущается что не очень заточен радар под странички с заголовками) Надо будет подсобрать набор наших хотелок к оформлению и мб что-то удастся сделать вместе с фронтами.

2024-04-15 11:58 UTC, sonulen commented on CONTRIBUTING.md
> +Так же это может быть ссылка на документацию по миграции, для примера можно посмотреть на accompanist insets.
этот блок весь - вставка кода - там вроде не работают ссылки =(

2024-04-16 11:53 UTC, sonulen commented on CONTRIBUTING.md
> +[assertj]: https://redmadrobot.github.io/techradar-android/libraries/assertj
это получается файл на гитхабе самом - а ссылки на уже сайт на pages - так что нет

2024-04-16 11:54 UTC, sonulen commented on radar/2024-04-03/junit.md
> +Плюсы Junit:
так ну это отдельной задачкой попытаюсь прикрутить - это не быстро, ок?

2024-04-16 12:24 UTC, sonulen commented on radar/2022-04-08/junit-assertion.md
> +title:      JUnit assertions
хм

я бы оставил исходя из того что на странице jUnit потом могут появится еще ссылки на другие страницы: для примера - кто то опишет аннотации и структуру теста, или например опишет потом тестовые раннеры + то что есть марафон и тоже ссылку можно будет на странице junit оставить

но не настаиваю, удалять не делать)

2024-04-16 14:56 UTC, osipxd commented on radar/2024-04-03/junit.md
> +Плюсы Junit:
Да, конечно

2024-04-16 15:04 UTC, osipxd commented on CONTRIBUTING.md
> +Так же это может быть ссылка на документацию по миграции, для примера можно посмотреть на accompanist insets.
Эх, жаль

2024-04-17 12:33 UTC, merged